---
# comment in manifest
applications:
    - name : ptj-message-service
      buildpacks: 
        - https://github.com/cloudfoundry/java-buildpack.git
      env:
        JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 12.+ } }'
      path: target/service-0.0.1-SNAPSHOT.jar
